




# Dependencies
markdown:         kramdown
highighter:       true

# Permalinks
permalink:        /jebennettlaw-v2/:title

# Setup
title:            JE Bennett Law
tagline:          "Helping the vulnerable"
description:      'JE Bennett Law is a Limited company incorporated in England and Wales (No.7875908), and is authorised and regulated by the Solicitors Regulation Authority (No.565975)'
url:              http://timbrazier.github.io/jebennettlaw-v2

author:
  name:           'Tim Brazier'
  url:            http://www.timbrazier.co.uk

paginate:         10

# Custom vars
version:          2.0.0

github:
  repo:           ''
baseurl:          '/jebennettlaw-v2'
